version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  basic-test : # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14.6

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - run:
          name: Get dependancies
          command: go get -t -d -v  ./...

      - run:
          name: Run tests 
          command: go test ./...

workflows:
  version: 2
  test-workflow:
    jobs:
      - basic-test